SELF_ANGULAR_VELOCITY: str = 'self_angular_velocity'
TARGET_ANGULAR_VELOCITY: str = 'target_angular_velocity'
TARGET_RELATIVE_DISPLACEMENT: str = 'target_relative_displacement'
TARGET_RELATIVE_VELOCITY: str = 'target_relative_velocity'
AGENT_ANGULAR_VELOCITIES: str = 'agent_angular_velocities'
CHASER_RELATIVE_DISPLACEMENTS: str = 'chaser_relative_displacements'
CHASER_RELATIVE_VELOCITIES: str = 'chaser_relative_velocities'
CHASER_ANGULAR_VELOCITIES: str = 'chaser_angular_velocities'
OBSTACLE_RELATIVE_DISPLACEMENTS: str = 'obstacle_relative_displacements'
TARGET_RELATIVE_DISPLACEMENTS: str = 'target_relative_displacements'
TARGET_RELATIVE_VELOCITIES: str = 'target_relative_velocities'
TARGET_ANGULAR_VELOCITIES: str = 'target_angular_velocities'


SELF: str = 'self'
AGENT: str = 'agent'
CHASER: str = 'chaser'
OBSTACLE: str = 'obstacle'
TARGET: str = 'target'


SELF_TARGET: str = 'self_target'
TARGET_SELF: str = 'target_self'
AGENT_CHASER: str = 'agent_chaser'
CHASER_AGENT: str = 'chaser_agent'
AGENT_OBSTACLE: str = 'agent_obstacle'
OBSTACLE_AGENT: str = 'obstacle_agent'
AGENT_TARGET: str = 'agent_target'
TARGET_AGENT: str = 'target_agent'
CHASER_CHASER: str = 'chaser_chaser'
CHASER_OBSTACLE: str = 'chaser_obstacle'
OBSTACLE_CHASER: str = 'obstacle_chaser'
CHASER_TARGET: str = 'chaser_target'
TARGET_CHASER: str = 'target_chaser'
OBSTACLE_TARGET: str = 'obstacle_target'
TARGET_OBSTACLE: str = 'target_obstacle'


ANTI_CLOCKWISE: str = 'anti_clockwise'
BACKWARD: str = 'backward'
CLOCKWISE: str = 'clockwise'
DOWN: str = 'down'
FORWARD: str = 'forward'
REST: str = 'rest'
UP: str = 'up'


CHASER_DIRECTIONS: str = 'chaser_directions'
CHASER_DISPLACEMENTS: str = 'chaser_displacements'
HAS_COLLIDED: str = 'has_collided'
HAS_CRASHED: str = 'has_crashed'
HAS_INTERCEPTED: str = 'has_intercepted'
OBSTACLE_DISPLACEMENTS: str = 'obstacle_displacements'
TARGET_DIRECTIONS: str = 'target_directions'
TARGET_DISPLACEMENTS: str = 'target_displacements'
TIME: str = 'time'
